# 노드를 베이스로 생성
FROM node:16.13.1

# mysql이 실행 할 준비가 되고 나서 실행할 수 있도록
#rds 사용 시 안써도 무방함
ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \  
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


# app 디렉토리 , working 디렉토리 생성

RUN npm install -g nodemon
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json .
RUN npm install

# Bundle app source
COPY . .

RUN chmod +x docker-entrypoint.sh  
ENTRYPOINT ./docker-entrypoint.sh

# Exports
EXPOSE 8080